"""Independent reference values for the devig solvers in engine/Devig.hpp.

Uses scipy's Brent solver, a different algorithm from the Newton-with-bisection
hybrid in power() and the plain bisection in shin(). Agreement between the two
is therefore evidence rather than circular confirmation.

Run:  python3 analytics/devig_reference.py
"""

import math

try:
    from scipy.optimize import brentq
    SOLVER = "scipy.optimize.brentq"
except ImportError:
    SOLVER = "fallback bisection (pip install scipy for a stronger check)"

    def brentq(f, a, b, xtol=1e-15, maxiter=400):
        fa = f(a)
        if fa * f(b) > 0:
            raise ValueError("root not bracketed")
        for _ in range(maxiter):
            m = 0.5 * (a + b)
            fm = f(m)
            if abs(fm) < xtol or (b - a) < xtol:
                return m
            if fa * fm < 0:
                b = m
            else:
                a, fa = m, fm
        return 0.5 * (a + b)


CASES = [
    [2.15, 3.40, 4.10],
    [1.50, 4.00, 7.00],
    [1.20, 8.00, 15.00],
    [2.90, 3.00, 3.10],
    [1.91, 1.91],
    [1.04, 21.00, 34.00],
    [8.00, 9.00, 10.00],
]


def solve_power_k(q):
    f = lambda k: sum(qi ** k for qi in q) - 1.0
    if f(1.0) <= 0.0:
        return 1.0
    hi = 2.0
    while f(hi) > 0 and hi < 1024:
        hi *= 2
    return brentq(f, 1.0, hi, xtol=1e-15)


def shin_probs(q, z, B):
    return [(math.sqrt(z * z + 4 * (1 - z) * qi * qi / B) - z) / (2 * (1 - z))
            for qi in q]


def solve_shin_z(q, B):
    if B <= 1.0:
        return 0.0
    g = lambda z: sum(shin_probs(q, z, B)) - 1.0
    return brentq(g, 0.0, 1.0 - 1e-9, xtol=1e-16)


print(f"// generated by analytics/devig_reference.py using {SOLVER}")
for odds in CASES:
    q = [1.0 / o for o in odds]
    B = sum(q)
    print()
    print(f"// odds {odds}   booksum {B:.10f}   overround {B - 1:.10f}")
    if B <= 1.0:
        print("// booksum <= 1: every method must return NoMarginToRemove")
        print(f"// raw implied  {['%.12f' % x for x in q]}")
        continue
    k = solve_power_k(q)
    z = solve_shin_z(q, B)
    print(f"// power  k = {k:.15f}")
    print(f"//        {['%.12f' % (qi ** k) for qi in q]}")
    print(f"// shin   z = {z:.15f}")
    print(f"//        {['%.12f' % x for x in shin_probs(q, z, B)]}")
    print(f"// mult   {['%.12f' % (qi / B) for qi in q]}")
